# Generated by Django 4.2.2 on 2025-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название курса"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фотография"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название урока"),
                ),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="Описание курса"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фотография"
                    ),
                ),
                (
                    "video_link",
                    models.TextField(max_length=200, verbose_name="Ссылка на видео"),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
