# Generated by Django 4.2.2 on 2025-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание курса"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Описание курса"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
